
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND COMPARISON EVENTUALLY EXIST FORALL GLOBALLY IMPLIES LPAREN NEXT NOT NUMBER OR PROB PROP RPAREN UNTILexpression : expression AND expression\n                  | expression OR expression\n                  | expression IMPLIES expressionexpression : FORALL expression UNTIL expression\n                  | EXIST expression UNTIL expressionexpression : FORALL GLOBALLY expression\n                  | FORALL NEXT expression\n                  | FORALL EVENTUALLY expression\n                  | EXIST GLOBALLY expression\n                  | EXIST NEXT expression\n                  | EXIST EVENTUALLY expressionexpression : NOT expressionexpression : LPAREN expression RPARENexpression : PROPexpression : PROB COMPARISON NUMBER LPAREN expression RPAREN'
    
_lr_action_items = {'FORALL':([0,2,3,4,5,8,9,10,12,13,14,16,17,18,25,29,37,],[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,]),'EXIST':([0,2,3,4,5,8,9,10,12,13,14,16,17,18,25,29,37,],[3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,]),'NOT':([0,2,3,4,5,8,9,10,12,13,14,16,17,18,25,29,37,],[4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,]),'LPAREN':([0,2,3,4,5,8,9,10,12,13,14,16,17,18,25,29,34,37,],[5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,37,5,]),'PROP':([0,2,3,4,5,8,9,10,12,13,14,16,17,18,25,29,37,],[6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,]),'PROB':([0,2,3,4,5,8,9,10,12,13,14,16,17,18,25,29,37,],[7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,]),'$end':([1,6,19,22,23,24,26,27,28,30,31,32,33,35,36,39,],[0,-14,-12,-1,-2,-3,-6,-7,-8,-9,-10,-11,-13,-4,-5,-15,]),'AND':([1,6,11,15,19,20,22,23,24,26,27,28,30,31,32,33,35,36,38,39,],[8,-14,8,8,8,8,8,8,8,8,8,8,8,8,8,-13,8,8,8,-15,]),'OR':([1,6,11,15,19,20,22,23,24,26,27,28,30,31,32,33,35,36,38,39,],[9,-14,9,9,9,9,9,9,9,9,9,9,9,9,9,-13,9,9,9,-15,]),'IMPLIES':([1,6,11,15,19,20,22,23,24,26,27,28,30,31,32,33,35,36,38,39,],[10,-14,10,10,10,10,10,10,10,10,10,10,10,10,10,-13,10,10,10,-15,]),'GLOBALLY':([2,3,],[12,16,]),'NEXT':([2,3,],[13,17,]),'EVENTUALLY':([2,3,],[14,18,]),'UNTIL':([6,11,15,19,22,23,24,26,27,28,30,31,32,33,35,36,39,],[-14,25,29,-12,-1,-2,-3,-6,-7,-8,-9,-10,-11,-13,-4,-5,-15,]),'RPAREN':([6,19,20,22,23,24,26,27,28,30,31,32,33,35,36,38,39,],[-14,-12,33,-1,-2,-3,-6,-7,-8,-9,-10,-11,-13,-4,-5,39,-15,]),'COMPARISON':([7,],[21,]),'NUMBER':([21,],[34,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,3,4,5,8,9,10,12,13,14,16,17,18,25,29,37,],[1,11,15,19,20,22,23,24,26,27,28,30,31,32,35,36,38,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression AND expression','expression',3,'p_expression_binary','parser.py',54),
  ('expression -> expression OR expression','expression',3,'p_expression_binary','parser.py',55),
  ('expression -> expression IMPLIES expression','expression',3,'p_expression_binary','parser.py',56),
  ('expression -> FORALL expression UNTIL expression','expression',4,'p_expression_ternary','parser.py',61),
  ('expression -> EXIST expression UNTIL expression','expression',4,'p_expression_ternary','parser.py',62),
  ('expression -> FORALL GLOBALLY expression','expression',3,'p_expression_unary','parser.py',67),
  ('expression -> FORALL NEXT expression','expression',3,'p_expression_unary','parser.py',68),
  ('expression -> FORALL EVENTUALLY expression','expression',3,'p_expression_unary','parser.py',69),
  ('expression -> EXIST GLOBALLY expression','expression',3,'p_expression_unary','parser.py',70),
  ('expression -> EXIST NEXT expression','expression',3,'p_expression_unary','parser.py',71),
  ('expression -> EXIST EVENTUALLY expression','expression',3,'p_expression_unary','parser.py',72),
  ('expression -> NOT expression','expression',2,'p_expression_not','parser.py',77),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','parser.py',82),
  ('expression -> PROP','expression',1,'p_expression_prop','parser.py',87),
  ('expression -> PROB COMPARISON NUMBER LPAREN expression RPAREN','expression',6,'p_expression_probability','parser.py',94),
]
